<?php

function pum_customer_views_api() {
  return array('api' => 3.0);
}

function pum_customer_get_role_ids($roles) {
  $rids = array();
  $available_roles = user_roles();
  foreach($roles as $role) {
    $rid = array_search($role, $available_roles);
    if ($rid !== false) {
      $rids[$rid] = $rid;
    }
  }
  
  return $rids;
}

function pum_customer_views_default_views() {
  $files = file_scan_directory(drupal_get_path('module', 'pum_customer'). '/views', '/.inc/');
  $views = array();
  civicrm_initialize();
  foreach ($files as $filepath => $file) {
    require $filepath;
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }
  return $views;
}

function _pum_customer_is_condition_completable_by_customer($activity_type_id) {
  $config = pum_customer_mycases_config::singleton();
  if (in_array($activity_type_id, $config->getCompletableConditions())) {
    return true;
  }
  return false;
}